#!/bin/bash
cd ../
branch=$(cat assetchains.json | jq -r '.[] | select (.ac_name == "STAKEDTROLL") | .branch')
chain="$HOME/staked/komodo/$branch/komodo-cli -ac_name=STAKEDTROLL"
echo "[STAKEDTROLL] Claiming faucet, check chat box for progress ..."
hex=$($chain faucetget | jq -r .hex) > /dev/null 2>&1
outcome1=$(echo $?)
$chain sendrawtransaction $hex > /dev/null 2>&1
outcome=$(echo $?)
if [[ $outcome != 0 ]] || [[ $outcome1 != 0 ]]; then
  echo -e "\033[1;31m Faucet claim failed, you can only claim from a new address, 3 times . Check chat box for more information. \033[0m"
else
  echo "Faucet get successful, enjoy your trolling!"
fi
